apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: todo-app-ns
type: Opaque # Indicates arbitrary user-defined data
data:
  POSTGRES_DB: eW91cl9hY3R1YWxfZGJfbmFtZQ== # e.g., dG9kb19kYg==
  POSTGRES_USER: eW91cl9hY3R1YWxfZGJfdXNlcg== # e.g., dXNlcg==
  POSTGRES_PASSWORD: eW91cl9hY3R1YWxfZGJfcGFzc3dvcmQ= # e.g., cGFzc3dvcmQ=