apiVersion: v1
kind: Service
metadata:
  name: db # This service name will be used by your Flask app (DB_HOST env var)
  namespace: todo-app-ns
  labels:
    app: todo-app
    tier: database
spec:
  selector:
    app: todo-app
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # Internal to the cluster