apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-db-pvc
  namespace: todo-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request 1GB of storage