apiVersion: v1
kind: Service
metadata:
  name: db # This service name ('db') is crucial; it's used by the Flask app's DB_HOST env var
  namespace: todo-app-ns
  labels:
    app: todo-app
    tier: database
spec:
  selector:
    app: todo-app
    tier: database # Selects pods with this label
  ports:
    - protocol: TCP
      port: 5432 # Service port
      targetPort: 5432 # Container port
  type: ClusterIP # Internal to the cluster, not exposed externally