apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-app       # Name of your application deployment
  namespace: todo-app-ns    # IMPORTANT: Must match the namespace defined in 00-namespace.yaml
                            # and the K8S_NAMESPACE environment variable in your main.yml
spec:
  replicas: 1               # Number of pods (instances) for your application
  selector:
    matchLabels:
      app: todo-flask-app   # Selector to link deployment to pods
  template:
    metadata:
      labels:
        app: todo-flask-app # Labels for the pods
    spec:
      containers:
      - name: todo-flask-container # IMPORTANT: This must match the container name
                                   # used in the 'kubectl set image' command in main.yml
        image: my-app:latest       # The image name and tag built locally by Minikube's Docker daemon
        imagePullPolicy: Never     # CRUCIAL for Minikube CI: Don't pull from remote registry
        ports:
        - containerPort: 8080      # The port your Flask application listens on (e.g., Gunicorn bind port)
        env: # Environment variables for your Flask app to connect to the DB
        # This will set the DATABASE_HOST environment variable in your Flask container
        - name: DATABASE_HOST
          value: todo-db-service   # Name of your database Kubernetes Service (e.g., from 04-db-service.yaml)
        # These will get DATABASE_USER from the todo-db-secret
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: todo-db-secret # <--- CORRECTED: This must match the name of your Secret
              key: POSTGRES_USER   # <--- CORRECTED: This must match the key in your Secret
        # These will get DATABASE_PASSWORD from the todo-db-secret
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-db-secret # <--- CORRECTED: This must match the name of your Secret
              key: POSTGRES_PASSWORD # <--- CORRECTED: This must match the key in your Secret

        # Add resource limits, probes, etc., if desired (assuming these are correctly indented)
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

        # Example probes - ensure these are correctly indented under 'containers'
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5