apiVersion: v1
kind: Service
metadata:
  name: todo-flask-service
  namespace: todo-app-ns
  labels:
    app: todo-app
    tier: web
spec:
  selector:
    app: todo-app
    tier: web
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 5000 # Internal container port
  type: LoadBalancer # For cloud providers (will get an external IP). Use NodePort for Minikube.
  # For Minikube/Kind, you might change type to NodePort:
  # type: NodePort