apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  namespace: todo-app-ns # Ensure this matches your deployment and namespace manifest
spec:
  selector:
    app: my-flask-app # Matches the labels in your deployment
  ports:
    - protocol: TCP
      port: 80        # The service port
      targetPort: 8080 # The container port (must match EXPOSE in Dockerfile)
      nodePort: 30000 # Choose a port in the 30000-32767 range for NodePort
  type: NodePort      # Exposes the service on a port on the Minikube VM