apiVersion: v1
kind: Service
metadata:
  name: todo-flask-service
  namespace: todo-app-ns
  labels:
    app: todo-app
    tier: web
spec:
  selector:
    app: todo-app
    tier: web
  ports:
    - protocol: TCP
      port: 80 # External port for the service
      targetPort: 5000 # Internal container port
  type: LoadBalancer # For cloud providers (will get an external IP).
  # For Minikube/Kind, you might change type to NodePort for local access:
  # type: NodePort
  # NodePort specific (if using type: NodePort above):
  # nodePort: 30000 # Optional: Specify a port in the 30000-32767 range